name: Dependabot
on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"
jobs:
  check-dependencies:
    runs-on: ubuntu-latest
    steps:
      - uses: marcoroth/dependabot-bump-together-action@v0.3.1
        with:
          dependencies: dependency_1, dependency_2
          package_managers: bundler, npm_and_yarn, pip
          directory: /
          branch: main
          username: x-access-token
          token: ${{ secrets.GITHUB_TOKEN }}
